### ISSUE TITLE
Overhead of a framework

### ISSUE THREAD

**Issue by fabpot** [phpbenchmarks/symfony-4-0#1]
First of all, thank you for this great project.

One interesting "feature" of a benchmark is to understand the framework performance overhead. The overhead added by a framework is interesting as there is no way you can get better performance. That's the baseline. And that's indeed the point of an hello world benchmark. One flaw in the current way you are doing it is that instead of having one project per benchmark, you have one project for all. Which means that the hello world benchmark is polluted by the added dependencies needed for the other benchmarks.

Would it make sense to create one repository per framework for the hello world benchmark and another one for more advanced tests?

**Comment by phpbenchmarks** [comment]
Hi, first, thanks !

Thats was my first idea : create one repository per benchmark type.
But i want to create 3 types : Hello World, 10 news list (use Twig, Doctrine, EventListener, Routing, etc) and REST Api (use EventListener, Routing, Serializer, etc).
If i create one repository per type, and per Symfony and other frameworks version, that's will be a lot of repository...

And in fact, i'm not sure there is an impact : i only add needed bundles in each types, as you can see it here :
https://github.com/phpbenchmarks/symfony-4-0/blob/master/config/helloworld/bundles.php
https://github.com/phpbenchmarks/symfony-4-0/blob/master/config/rest/bundles.php

So, for example, for Hello World benchmark, files for REST Api are here, but not included / used. I don't think it has a real impact ?

**Comment by fabpot** [comment]
It does have an impact as Symfony automatically enable services based on installed dependencies. We could argue that the impact is minimal of course but the whole point of the hello world is to only enable the bare minimum.

I think 2 repos would be enough (per framework): one for the hello world and the other one with everything else. Again, just because the hello world is very specific.

**Comment by phpbenchmarks** [comment]
We could argue, and that's the goal of this website : be precise !

I understand what you mean, i will make some tests as soon as possible.
If there is a difference, as minimalistic it is, i will change it !

Thanks for your message, i appreciate ;)

**Comment by fabpot** [comment]
Thank you!

**Comment by phpbenchmarks** [comment]
I've made some tests, by removing  `symfony/console`, `symfony/serializer-pack` and `symfony/translation` onbly for Hello World benchmark.
Nothing changes, as you can see :

| Concurrency | ms/req (with too much dependencies) | ms/req (with only required dependencies) |
| -----------------| --------------------------------------- | -------------------------------------------- |
| 1 | 1.156 | 1.186 |
| 5 | 0.897 | 0.888 |
| 10 | 1.644 | 1.610 |
| 20 | 3.341 | 3.253 |

But to take your message into account, do you think `create a composer.json per benchmark type` (Hello World, REST Api) could be a good idea, instead of creating a new repository ? Only difference between benchmark types are dependencies, so if i do that, to mee, that's ok.

**Comment by phpbenchmarks** [comment]
@fabpot Do you have any answer to my proposal ?

**Comment by fabpot** [comment]
Having a different composer.json does not look enough to me as the configurations are probably different as well, no?

**Comment by phpbenchmarks** [comment]
Yes it is, that's why i create a directory in `config/` for each benchmark type :
`https://github.com/phpbenchmarks/symfony-4-0/tree/master/config/helloworld`
`https://github.com/phpbenchmarks/symfony-4-0/tree/master/config/rest`

**Comment by phpbenchmarks** [comment]
@fabpot Another idea : create a branch for `Hello World`, and another one for `REST Api`. Each branch will have their own `composer.json`, configuration, etc, and **no files from other benchmark**.

**Comment by Tobion** [comment]
Using brances seems to me like the best solution. Then you can easily see the diff and you can use the standard setup for each benchmark instead of having many composer.json/locks and custom configuration structure.

**Comment by phpbenchmarks** [comment]
Job done: each benchmark is now on it's own branch.

I will relaunch Symfony 4 benchmarks, cause it can have an impact, but not older version (no changes).
