### ISSUE TITLE
Could not open input file: app/console

### ISSUE THREAD

**Issue by FDiskas** [phpbenchmarks/symfony-4-0#2]
You should fix that by changing to `bin/console`

https://github.com/phpbenchmarks/symfony-4-0/blob/dc8c26932d0c1b96aecb21195f885baaa59c96ba/init_benchmark.sh#L32

**Comment by phpbenchmarks** [comment]
Fix : https://github.com/phpbenchmarks/symfony-4-0/commit/8318f8f0a256092a6e68a583a0731373c55081d0

Thanks !
